name: christopherbishop
favicon: null
layout_spectrum: 0.91054
typography_spectrum: 0.52054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040c64'
    - '#0454b4'
    - '#94cbfa'
    - '#53a5e9'
    - '#dbf2fc'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.620938834734261
  rhythmicContrast: 0.5
purpose: []
